name: Al-Khaser
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Setup repo
      uses: actions/checkout@v3
      with:
        repository: "LordNoteworthy/al-khaser"

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1.3

    - name: Build x86
      run: msbuild /m /p:Platform=x86 /p:Configuration=Release al-khaser.sln

    - name: Build x64
      run: msbuild /m /p:Platform=x64 /p:Configuration=Release al-khaser.sln

    - name: Zip x86 Binaries
      run: 7z a -t7z -m0=lzma2 -mx=9 -mfb=64 -md=32m -mhe=on -p"yug69gG89T98HGUY8y" al-khaser_x86.7z al-khaser_x86.exe

    - name: Zip x64 Binaries
      run: 7z a -t7z -m0=lzma2 -mx=9 -mfb=64 -md=32m -mhe=on -p"yug69gG89T98HGUY8y" al-khaser_x64.7z al-khaser_x64.exe

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
          tag_name: "Al-Khaser-${{ github.run_id }}"
          body: "Password:yug69gG89T98HGUY8y"
          files: |
            al-khaser_x86.7z
            al-khaser_x64.7z
