name: Build-pafish
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup repo
      uses: actions/checkout@v2
      with:
        repository: "a0rtega/pafish"

    - name: Install MinGW
      uses: egor-tensin/setup-mingw@v2

    - name: Build x86
      run: cd pafish/ && make -f Makefile.linux

    - name: Build x64
      run: cd pafish/ && make -f Makefile64.linux

    - name: Zip x86 Binaries
      run: 7z a -t7z -m0=lzma2 -mx=9 -mfb=64 -md=32m -mhe=on -p"87goff57qScYw57CCV" pafish_x86.7z ./pafish/Output/MingW/pafish.exe

    - name: Zip x64 Binaries
      run: 7z a -t7z -m0=lzma2 -mx=9 -mfb=64 -md=32m -mhe=on -p"87goff57qScYw57CCV" pafish_x64.7z ./pafish/Output/MingW/pafish64.exe
        
    - name: Upload x86 Binaries
      uses: actions/upload-artifact@v1
      with:
          name: x86
          path: "pafish_x86.7z"

    - name: Upload x64 Binaries
      uses: actions/upload-artifact@v1
      with:
          name: x64
          path: "pafish_x64.7z"

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
          files: |
            pafish_x86.7z
            pafish_x64.7z
